### ISSUE TITLE
Update plugin to 1.17.1 - JAVA 16

### ISSUE THREAD

**Issue by ErythroCraft** [hockeymikey/NewerWand#1]
Hello

can you give an update to fix this ERROR please?

[20:25:06] [Server thread/ERROR]: Error occurred while enabling NewerWand v1.1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/selections/Selection
        at mn.hockeymikey.newerwand.NewerWand.registerListeners(NewerWand.java:280) ~[?:?]
        at mn.hockeymikey.newerwand.NewerWand.init(NewerWand.java:276) ~[?:?]
        at mn.hockeymikey.newerwand.NewerWand.onEnable(NewerWand.java:70) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:520) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:434) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.selections.Selection
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3262-Spigot-dc75aca-f0f801e]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more

**Comment by hockeymikey** [comment]
@ErythroCraft People actually use this plugin? That's really cool, I'll see what I can do. I think I updated the NewWand plugin to 1.17.1 and the new WorldEdit/WorldGuard apis (which is parent of NewerWand, same thing just amped up). That was a few months ago, should be a quick one shot.

**Comment by ErythroCraft** [comment]
I would install it. But everytime my server is on latest spigot version.

you can close this issue, if you don't want update your plugin.

**Comment by ErythroCraft** [comment]
Now it's 1.18.2

**Comment by hockeymikey** [comment]
I've just been busy, that's the main thing and no real financial incentive vs the stresses of work isn't a motivating combo.

**Comment by ErythroCraft** [comment]
ok

**Comment by ErythroCraft** [comment]
You can do it so.

1. Create 3 plugins more on spigot.
2. Wait for an minimum of downloads.
3. Than you can sell this plugin.

I will buy it, if you worked. But I can not give out payments for one plugin.
If you want have ideas and you can type JAVA fine, I can give you any.

**Comment by hockeymikey** [comment]
@ErythroCraft I don't have a huge desire to sell it, I don't think it would make much money, would it? And you can't give out payments for a plugin but you'd wanna spend $10 on one? I'm confused.  Ideas for what? See the big thing for me is time, I do not have a lot of it but if you keep bugging me it does keep the project in my forefront and encourages me to get it done.

**Comment by ErythroCraft** [comment]
Is ok. I don't use this plugin and was creating an custom item with ExecutableItems.

**Comment by hockeymikey** [comment]
https://worldedit.enginehub.org/en/latest/api/examples/local-sessions/#getting-a-player-s-selection

**Comment by hockeymikey** [comment]
https://github.com/hockeymikey/NewerWand/commit/c50139ad6c8a43e136214015acfeb0469e828327
https://www.spigotmc.org/resources/newer-wand.5236/update?update=491328

**Comment by hockeymikey** [comment]
Sorry it took so long.
